export default {
  ADD_NODE: 'ADD_NODE',
  DELETE_NODES: 'DELETE_NODES',
  SINGLE_SELECT_NODE: 'SINGLE_SELECT_NODE',
  MULTI_SELECT_NODE: 'MULTI_SELECT_NODE',
  CLEAR_SELECTED_NODES: 'CLEAR_SELECTED_NODES',
  DRAG_NODE: 'DRAG_NODE',
  STOP_DRAGGING_NODE: 'STOP_DRAGGING_NODE',
  START_DRAGGING_POINT: 'START_DRAGGING_POINT',
  DRAG_POINT: 'DRAG_POINT',
  STOP_DRAGGING_POINT: 'STOP_DRAGGING_POINT',
  BRING_NODES_TO_FRONT: 'BRING_NODES_TO_FRONT',
  SEND_NODES_TO_BACK: 'SEND_NODES_TO_BACK',
}