// @flow

export const ADD_NODE = 'ADD_NODE';
export const DELETE_NODES = 'DELETE_NODES';
export const SINGLE_SELECT_NODE = 'SINGLE_SELECT_NODE';
export const MULTI_SELECT_NODE = 'MULTI_SELECT_NODE';
export const CLEAR_SELECTED_NODES = 'CLEAR_SELECTED_NODES';
export const DRAG_NODE = 'DRAG_NODE';
export const STOP_DRAGGING_NODE = 'STOP_DRAGGING_NODE';
export const START_DRAGGING_POINT = 'START_DRAGGING_POINT';
export const DRAG_POINT = 'DRAG_POINT';
export const STOP_DRAGGING_POINT = 'STOP_DRAGGING_POINT';
export const BRING_NODES_TO_FRONT = 'BRING_NODES_TO_FRONT';
export const SEND_NODES_TO_BACK = 'SEND_NODES_TO_BACK';
export const SELECT_ALL_NODES = 'SELECT_ALL_NODES';
